name: Timeout Example
on: [push]
jobs:
  test-timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Run a sample command
        run: echo "This job will timeout after 5 minutes if it runs longer"

      - name: simulate long running task
        run: |
          echo "Sleeping for 10 minutes"
          sleep 600